name: Build and Release Binaries

run-name: Running tests and checks for policies

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    permissions:
      contents: read
    uses: ./.github/workflows/test.yml

  release:
    runs-on: ubuntu-latest

    needs:
      - test

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
